### ISSUE TITLE
Installation not working for Satellite 6.6

### ISSUE THREAD

**Issue by stdevel** [oasis-roles/satellite#7]
The installation of Satellite 6.6 (*based on Foreman 1.22*) currently fails as the Docker support was removed. Anyhow, the answers file template (``satellite-answers.yaml``) still contains the Docker line:
```
foreman::plugin::docker: true
```
See also https://github.com/oasis-roles/satellite/blob/master/templates/satellite-answers.yaml#L58

This was also mentioned here: https://github.com/oasis-roles/satellite/issues/5#issuecomment-540616450_

Foreman Community thread with the same problem: https://community.theforeman.org/t/receiving-no-puppet-module-parser-is-installed-error-when-trying-to-run-foreman-installer-upgrade/14717/2

Error message:
```RUNNING HANDLER [oasis_roles.satellite : run satellite installer] **************
    fatal: [rhel7]: FAILED! => {"changed": true, "cmd": ["satellite-installer", "--scenario", "satellite", "--dont-save-answers"], "delta": "0:00:01.834879", "end": "2020-02-19 13:46:30.398727", "msg": "non-zero return code", "rc": 1, "start": "2020-02-19 13:46:28.563848", "stderr": "/usr/share/gems/gems/kafo-3.0.0/lib/kafo/puppet_module.rb:69:in `parse': No Puppet module parser is installed and no cache of the file /usr/share/foreman-installer/modules/foreman/manifests/plugin/docker.pp is available. Please check debug logs and install optional dependencies for the parser. (Kafo::ParserError)\n\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/configuration.rb:96:in `block in modules'\n\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/configuration.rb:96:in `map'\n\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/configuration.rb:96:in `modules'\n\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/configuration.rb:214:in `params'\n\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/configuration.rb:224:in `preset_defaults_from_puppet'\n\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/kafo_configure.rb:285:in `set_parameters'\n\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/kafo_configure.rb:100:in `initialize'\n\tfrom /usr/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `new'\n\tfrom /usr/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'\n\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/kafo_configure.rb:163:in `run'\n\tfrom /sbin/satellite-installer:8:in `<main>'", "stderr_lines": ["/usr/share/gems/gems/kafo-3.0.0/lib/kafo/puppet_module.rb:69:in `parse': No Puppet module parser is installed and no cache of the file /usr/share/foreman-installer/modules/foreman/manifests/plugin/docker.pp is available. Please check debug logs and install optional dependencies for the parser. (Kafo::ParserError)", "\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/configuration.rb:96:in `block in modules'", "\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/configuration.rb:96:in `map'", "\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/configuration.rb:96:in `modules'", "\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/configuration.rb:214:in `params'", "\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/configuration.rb:224:in `preset_defaults_from_puppet'", "\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/kafo_configure.rb:285:in `set_parameters'", "\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/kafo_configure.rb:100:in `initialize'", "\tfrom /usr/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `new'", "\tfrom /usr/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'", "\tfrom /usr/share/gems/gems/kafo-3.0.0/lib/kafo/kafo_configure.rb:163:in `run'", "\tfrom /sbin/satellite-installer:8:in `<main>'"], "stdout": "", "stdout_lines": []}
```

When removing the line from the file, installation works again.

**Comment by ogajduse** [comment]
#8  should fix this

**Comment by cojmckee** [comment]
@stdevel  added this issue to the new role
https://github.com/oasis-roles/ansible_collection_satellite/issues/30
